-- AlterTable
ALTER TABLE `Product` ADD COLUMN `brand` VARCHAR(191) NULL,
    ADD COLUMN `condition` VARCHAR(191) NULL,
    ADD COLUMN `location` VARCHAR(191) NULL,
    ADD COLUMN `maxStockLevel` INTEGER NULL,
    ADD COLUMN `minStockLevel` INTEGER NULL,
    ADD COLUMN `model` VARCHAR(191) NULL,
    ADD COLUMN `quality` VARCHAR(191) NOT NULL DEFAULT 'NEW',
    ADD COLUMN `supplier` VARCHAR(191) NULL,
    ADD COLUMN `supplierContact` VARCHAR(191) NULL,
    ADD COLUMN `tags` VARCHAR(191) NULL,
    ADD COLUMN `warranty` INTEGER NULL;
